	printf "// Generated by PV Tools\n\n" > vram.h
	printf "#ifndef _VRAM_H\n#define _VRAM_H\n" >> vram.h
	#xxd -s 7 -l 10240 -i -n vram vram.SC5 | sed 's/unsigned char/const unsigned char/' | sed 's/unsigned int/const unsigned int/' >> vram.h
	head -c 10247 vram.SC5 | tail -c 10240 > vram.dump
	split vram.dump -b 4096
	zx0 -f xaa
	zx0 -f xab
	zx0 -f xac
	#./lz48 -i vram.dump -o vram.dump.lz48
	xxd -i -n vram1 xaa.zx0 | sed 's/unsigned char/const unsigned char/' | sed 's/unsigned int/const unsigned int/' >> vram.h
	xxd -i -n vram2 xab.zx0 | sed 's/unsigned char/const unsigned char/' | sed 's/unsigned int/const unsigned int/' >> vram.h
	xxd -i -n vram3 xac.zx0 | sed 's/unsigned char/const unsigned char/' | sed 's/unsigned int/const unsigned int/' >> vram.h
	#xxd -i -n vram vram.decomp | sed 's/unsigned char/const unsigned char/' | sed 's/unsigned int/const unsigned int/' >> vram.h
	#xxd -i -n vram vram.dump.lz48 | sed 's/unsigned char/const unsigned char/' | sed 's/unsigned int/const unsigned int/' >> vram.h
	xxd -s 30343 -i -n vram_pal vram.SC5 | sed 's/unsigned char/const unsigned char/' | sed 's/unsigned int/const unsigned int/'>> vram.h
	printf "\n\n#else\n\nextern const unsigned char *vram[];\nextern const unsigned char *vram_pal[];\n"  >> vram.h
	printf "#endif // _VRAM_H" >> vram.h
